apiVersion: 1.0.0
metadata:
  generateName: camel-demo-
projects:
  - name: camel-demo
    source:
      type: github
      location: 'https://github.com/abkieling/camel-demo.git'
components:
  - id: redhat/java11/latest
    type: chePlugin
  - id: redhat/vscode-apache-camel/latest
    type: chePlugin
  - id: redhat/vscode-openshift-connector/latest
    type: chePlugin
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - type: dockerimage
    alias: maven
    image: 'registry.redhat.io/codeready-workspaces/plugin-java11-rhel8@sha256:cff9e47f83c6140d442721ed4d78e029a55f98bdca8efffbba8513656a1b28a7'
    env:
      - name: JAVA_OPTS
        value: '-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/jboss'
      - name: MAVEN_OPTS
        value: $(JAVA_OPTS)
    memoryLimit: 512Mi
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/jboss/.m2
    endpoints:
      - name: quarkus-development-server
        port: 8080
      - attributes:
          path: /
        name: hello
        port: 8080
      - attributes:
          public: 'false'
        name: debug
        port: 5005
      - attributes:
          public: 'false'
        name: tests
        port: 8081
commands:
  - name: 1. Package the application
    actions:
      - type: exec
        component: maven
        command: mvn package
        workdir: '${CHE_PROJECTS_ROOT}/camel-demo'
  - name: 2. Start Quarkus in devmode (hot deploy + debug)
    actions:
      - type: exec
        component: maven
        command: 'mvn compile quarkus:dev -Dquarkus.live-reload.instrumentation=false'
        workdir: '${CHE_PROJECTS_ROOT}/camel-demo'
  - name: Attach remote debugger
    actions:
      - type: vscode-launch
        referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "type": "java",
                "request": "attach",
                "name": "Attach to Remote Quarkus App",
                "hostName": "localhost",
                "port": 5005
              }
            ]
          }
